version: '3.7'

services:
  app:
    image: tijmenwierenga/commenting-system:latest
    ports:
    - 80:80
    environment:
      MYSQL_DSN: mysql:host=mariadb;dbname=api
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: demo
      SECRET_KEY: 6d910f987a5b31c874d780d5aa07249b3b5203aad5b6844f611c92ea200f7791

  mariadb:
    image: mariadb:10.4
    volumes:
    - mariadb_data:/var/lib/mysql
    - .sql/exports:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: api

  docs:
    image: redocly/redoc:latest
    volumes:
    - ./public/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    ports:
    - 8080:80
    environment:
      SPEC_URL: openapi.yaml

volumes:
  mariadb_data: ~