version: '3.7'

services:
  app:
    image: tijmenwierenga/commenting-system:latest
    ports:
    - 80:80

  mariadb:
    image: mariadb:10.4
    volumes:
    - mariadb_data:/var/lib/mysql
    - .sql/exports:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: api

volumes:
  mariadb_data: ~